local END_COLOR="\e[0m"
local RED="\e[31m"
local GREEN="\e[32m"
local YELLOW="\e[33m"
local BLUE="\e[34m"
local MAGENTA="\e[35m"
local CYAN="\e[36m"

local TAB=$'    '
local DTAB=$"$TAB$TAB"

# Icons temporarily disabled because of tertminal font.
local IADD="+ "
local IARRW="↳ "
local IBRCH="☉ "
local ICONF="✸ "
local IUNDO="⟲ "
local IDOT="· "
local IDWLD="⤓ "
local IERR="⤫ "
local IINFO="🛈 "
local IINP="$ "
local ILESS="- "
local IMOD="☢ "
local INEWS="★ "
local IOK="✓ "
local IPLUS="+ "
local IREAD="⚙ "
local ISTAR="⋆ "
local IUNTR="♦ "
local IVAL="$ "
local IWARN="⚠ "

# Icons temporarily disabled because of tertminal font.
# local IADD=""
# local IARRW="> "
# local IBRCH=""
# local ICONF=""
# local IUNDO=""
# local IDOT="· "
# local IDWLD=""
# local IERR=""
# local IINFO=""
# local IINP=""
# local ILESS="- "
# local IMOD=""
# local INEWS=""
# local IOK=""
# local IPLUS="+ "
# local IREAD=""
# local ISTAR="⋆ "
# local IUNTR=""
# local IVAL=""
# local IWARN=""
